# Generated by Django 3.1.7 on 2021-06-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2', '0003_remove_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
    ]
