# Generated by Django 3.1.7 on 2021-06-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2', '0004_auto_20210609_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
