# Generated by Django 3.1.7 on 2021-06-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2', '0005_remove_comments_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='enq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ques', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
