# Generated by Django 3.1.7 on 2021-08-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2', '0009_auto_20210804_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='dem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='demo/')),
            ],
        ),
    ]
