# Generated by Django 3.1.7 on 2021-08-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2', '0010_dem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
