# Generated by Django 3.1.7 on 2021-08-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2', '0011_auto_20210804_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(default='admin', max_length=254),
        ),
    ]
