# Generated by Django 3.1.7 on 2021-08-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2', '0013_auto_20210804_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(default='rk0901308@gmail.com', max_length=254),
        ),
    ]
